import { useEffect, useMemo, useState } from 'react'
import { createPortal } from 'react-dom'
import type { Language } from '../i18n'
import { moveRecordToRecycleBin } from '../utils/recycleBin'
import { toast } from '../utils/toast'

type Customer={id:string;name:string;phone?:string;email?:string;address?:string;notes?:string;vip?:boolean;status?:'Active'|'Inactive';createdAt?:string}
type Invoice={id:string;invoiceNo:string;date:string;createdAt?:string;customerId?:string;customerName:string;currency?:string;total:number;paid:number;remaining:number;discount?:number;profit?:number;items?:any[]}
const n=(v:unknown)=>Number.parseFloat(String(v??0))||0
const load=<T,>(k:string,f:T):T=>{try{const r=localStorage.getItem(k);return r?JSON.parse(r):f}catch{return f}}
const save=(k:string,v:unknown)=>{localStorage.setItem(k,JSON.stringify(v));window.dispatchEvent(new CustomEvent('pharma:data-changed'))}
const sym=(c='AFN')=>c==='AFN'?'؋':c==='USD'?'$':c
const money=(v:number,c='AFN')=>`${v.toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2})} ${sym(c)}`
const copy={
English:{title:'Customer Management',sub:'Manage customer relationships',add:'Add Customer',print:'Print Report',total:'Total Customers',vip:'VIP Customers',purchases:'Total Purchases',pending:'Total Pending',search:'Search by name, phone or email...',allStatus:'All statuses',active:'Active',inactive:'Inactive',payment:'Payment status',paid:'Paid',pendingPay:'Pending',allTime:'All time',today:'Today',week:'Weekly',month:'Monthly',year:'Yearly',custom:'Custom',customers:'Customers',none:'No customers found',hint:'Add your first customer',contact:'Contact',orders:'Purchases',balance:'Pending',status:'Status',actions:'Actions',profile:'View Profile',edit:'Edit',del:'Delete',modalAdd:'Add New Customer',modalEdit:'Edit Customer',name:'Name',phone:'Phone',email:'Email',address:'Address',notes:'Notes',vipCustomer:'VIP Customer',cancel:'Cancel',save:'Save Customer',confirm:'Delete this customer?',namePh:'Customer name',phonePh:'Phone number',emailPh:'Email address',addressPh:'Address',notesPh:'Additional notes'},
دری:{title:'مدیریت مشتریان',sub:'مدیریت روابط مشتریان',add:'افزودن مشتری',print:'چاپ گزارش',total:'مجموع مشتریان',vip:'مشتریان ویژه',purchases:'مجموع خریدها',pending:'مجموع معلق',search:'جستجو با نام، تلفون یا ایمیل...',allStatus:'همه وضعیت‌ها',active:'فعال',inactive:'غیرفعال',payment:'وضعیت پرداخت',paid:'پرداخت شده',pendingPay:'معلق',allTime:'همه وقت',today:'امروز',week:'هفتگی',month:'ماهانه',year:'سالانه',custom:'سفارشی',customers:'مشتریان',none:'مشتری یافت نشد',hint:'اولین مشتری خود را اضافه کنید',contact:'تماس',orders:'خریدها',balance:'معلق',status:'وضعیت',actions:'عملیات',profile:'مشاهده پروفایل',edit:'ویرایش',del:'حذف',modalAdd:'افزودن مشتری جدید',modalEdit:'ویرایش مشتری',name:'نام',phone:'تلفون',email:'ایمیل',address:'آدرس',notes:'یادداشت',vipCustomer:'مشتری VIP',cancel:'لغو',save:'افزودن مشتری',confirm:'این مشتری حذف شود؟',namePh:'نام مشتری',phonePh:'شماره تلفون',emailPh:'آدرس ایمیل',addressPh:'آدرس',notesPh:'یادداشت‌های اضافی'},
پښتو:{title:'د پیرودونکو مدیریت',sub:'د پیرودونکو اړیکې مدیریت کړئ',add:'پیرودونکی اضافه کړئ',print:'راپور چاپ',total:'ټول پیرودونکي',vip:'ځانګړي پیرودونکي',purchases:'ټولې پېرودنې',pending:'ټول پاتې',search:'د نوم، تلفون یا ایمیل له مخې لټون...',allStatus:'ټول حالتونه',active:'فعال',inactive:'غیرفعال',payment:'د تادیې حالت',paid:'ورکړل شوی',pendingPay:'پاتې',allTime:'ټول وخت',today:'نن',week:'اونیز',month:'میاشتنی',year:'کلنی',custom:'ځانګړی',customers:'پیرودونکي',none:'پیرودونکی ونه موندل شو',hint:'لومړی پیرودونکی اضافه کړئ',contact:'اړیکه',orders:'پېرودنې',balance:'پاتې',status:'حالت',actions:'عملیات',profile:'پروفایل وګورئ',edit:'سمون',del:'حذف',modalAdd:'نوی پیرودونکی',modalEdit:'پیرودونکی سمول',name:'نوم',phone:'تلفون',email:'ایمیل',address:'پته',notes:'یادښتونه',vipCustomer:'VIP پیرودونکی',cancel:'لغوه',save:'خوندي کول',confirm:'دا پیرودونکی حذف شي؟',namePh:'د پیرودونکي نوم',phonePh:'تلفون شمېره',emailPh:'ایمیل',addressPh:'پته',notesPh:'اضافي یادښتونه'}
} as const

function I({name,className=''}:{name:string;className?:string}){return <span className={`inline-grid h-5 w-5 place-items-center text-[15px] leading-none ${className}`} aria-hidden="true">{name}</span>}

export default function Customers({language,onOpenCustomer,globalSearch=''}:{language:Language;onOpenCustomer:(id:string)=>void;globalSearch?:string}){
 const t=copy[language]??copy.English; const [customers,setCustomers]=useState<Customer[]>(()=>load('customers',[])); const [invoices,setInvoices]=useState<Invoice[]>(()=>load('billingInvoices',[]));
 const [search,setSearch]=useState(''); const [status,setStatus]=useState('all'); const [pay,setPay]=useState('all'); const [dateFilter,setDateFilter]=useState('all'); const [modal,setModal]=useState(false); const [editing,setEditing]=useState<Customer|null>(null); const [menu,setMenu]=useState<string|null>(null)
 const empty={id:'',name:'',phone:'',email:'',address:'',notes:'',vip:false,status:'Active' as const}; const [form,setForm]=useState<Customer>(empty)
 useEffect(()=>{const f=()=>{setCustomers(load('customers',[]));setInvoices(load('billingInvoices',[]))};window.addEventListener('pharma:data-changed',f);window.addEventListener('storage',f);return()=>{window.removeEventListener('pharma:data-changed',f);window.removeEventListener('storage',f)}},[])
 useEffect(()=>setSearch(globalSearch),[globalSearch])
 useEffect(()=>{if(!modal)return;const old=document.body.style.overflow;document.body.style.overflow='hidden';return()=>{document.body.style.overflow=old}},[modal])
 const salesFor=(c:Customer)=>invoices.filter(i=>String(i.customerId||'')===String(c.id)||(!i.customerId&&i.customerName===c.name))
 const rows=useMemo(()=>customers.map(c=>{const sales=salesFor(c);return{...c,total:sales.reduce((s,i)=>s+n(i.total),0),pending:sales.reduce((s,i)=>s+n(i.remaining),0),orders:sales.length,last:sales[0]?.date||c.createdAt?.slice(0,10)||''}}).filter(c=>{const q=search.toLowerCase();if(q&&!`${c.name} ${c.phone||''} ${c.email||''}`.toLowerCase().includes(q))return false;if(status!=='all'&&(c.status||'Active').toLowerCase()!==status)return false;if(pay==='paid'&&c.pending>0)return false;if(pay==='pending'&&c.pending<=0)return false;if(dateFilter!=='all'&&c.last){const d=new Date(c.last),now=new Date();const days=(+now-+d)/86400000;if(dateFilter==='today'&&days>1)return false;if(dateFilter==='week'&&days>7)return false;if(dateFilter==='month'&&days>31)return false;if(dateFilter==='year'&&days>366)return false}return true}),[customers,invoices,search,status,pay,dateFilter])
 const totals=customers.reduce((a,c)=>{const s=salesFor(c);a.p+=s.reduce((x,i)=>x+n(i.total),0);a.r+=s.reduce((x,i)=>x+n(i.remaining),0);return a},{p:0,r:0})
 const openAdd=()=>{setEditing(null);setForm({...empty,id:`customer-${Date.now()}`});setModal(true)}; const openEdit=(c:Customer)=>{setEditing(c);setForm({...empty,...c});setModal(true);setMenu(null)}
 const persist=()=>{if(!form.name.trim())return;const wasEditing=!!editing;const next=editing?customers.map(c=>c.id===editing.id?{...form,id:editing.id}:c):[{...form,createdAt:new Date().toISOString()},...customers];setCustomers(next);save('customers',next);setModal(false);toast.success(wasEditing?t.edit:t.add, form.name)}
 const remove=(c:Customer)=>{setMenu(null);if(!confirm(t.confirm))return;moveRecordToRecycleBin('customers',c,c.name);const next=customers.filter(x=>x.id!==c.id);setCustomers(next);save('customers',next);toast.warning(t.del, c.name)}
 return <div className="w-full pb-8">
  <div className="flex flex-col gap-4 md:flex-row md:items-start md:justify-between"><div><h1 className="text-2xl font-extrabold">{t.title}</h1><p className="mt-1 text-sm text-slate-500">{t.sub}</p></div><div className="flex gap-2"><button onClick={openAdd} className="inline-flex h-10 items-center gap-2 rounded-lg bg-[#172a57] px-4 text-sm font-bold text-white"><I name="＋"/>{t.add}</button><button onClick={()=>window.print()} className="inline-flex h-10 items-center gap-2 rounded-lg border border-slate-200 bg-white px-4 text-sm font-semibold dark:border-[#24365f] dark:bg-[#111a2c] dark:text-white"><I name="🖨"/>{t.print}</button></div></div>
  <div className="mt-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Card title={t.total} value={String(customers.length)} icon="👥" accent="border-sky-400 bg-sky-50"/><Card title={t.vip} value={String(customers.filter(c=>c.vip).length)} icon="☆" accent="border-emerald-400 bg-emerald-50"/><Card title={t.purchases} value={money(totals.p)} icon="▣" accent="border-[#172a57] bg-slate-100"/><Card title={t.pending} value={money(totals.r)} icon="$" accent="border-amber-400 bg-amber-50"/></div>
  <div className="app-panel mt-5 grid gap-3 rounded-xl border border-slate-200 bg-white p-4 dark:border-[#24365f] dark:bg-[#111a2c] md:grid-cols-[1fr_120px_130px_130px]"><div className="relative"><span className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400 rtl:left-auto rtl:right-3">⌕</span><input className="form-control pl-9 rtl:pl-3 rtl:pr-9" value={search} onChange={e=>setSearch(e.target.value)} placeholder={t.search}/></div><select className="form-control" value={status} onChange={e=>setStatus(e.target.value)}><option value="all">{t.allStatus}</option><option value="active">{t.active}</option><option value="inactive">{t.inactive}</option></select><select className="form-control" value={pay} onChange={e=>setPay(e.target.value)}><option value="all">{t.payment}</option><option value="paid">{t.paid}</option><option value="pending">{t.pendingPay}</option></select><select className="form-control" value={dateFilter} onChange={e=>setDateFilter(e.target.value)}><option value="all">{t.allTime}</option><option value="today">{t.today}</option><option value="week">{t.week}</option><option value="month">{t.month}</option><option value="year">{t.year}</option></select></div>
  <div className="app-panel mt-5 rounded-xl border border-slate-200 bg-white p-5 dark:border-[#24365f] dark:bg-[#111a2c]"><div className="mb-5 flex items-center justify-between"><h2 className="font-bold">{t.customers} ({rows.length})</h2><I name="👥"/></div>{!rows.length?<div className="grid min-h-[190px] place-items-center text-center"><div><div className="text-4xl opacity-30">👥</div><div className="mt-3 font-bold">{t.none}</div><div className="text-sm text-slate-400">{t.hint}</div></div></div>:<div className="overflow-x-auto"><table className="w-full min-w-[850px] text-sm"><thead><tr className="border-b text-slate-500"><th className="p-3 text-start">{t.name}</th><th className="p-3 text-start">{t.contact}</th><th className="p-3 text-start">{t.orders}</th><th className="p-3 text-start">{t.balance}</th><th className="p-3 text-start">{t.status}</th><th className="p-3 text-start">{t.actions}</th></tr></thead><tbody>{rows.map(c=><tr key={c.id} className="cursor-pointer border-b border-slate-200 last:border-0 hover:bg-slate-50 dark:border-[#24365f] dark:hover:bg-white/5" onClick={()=>onOpenCustomer(c.id)}><td className="p-3 font-bold">{c.name}{c.vip&&<span className="ms-2 text-amber-400">★</span>}</td><td className="p-3"><div>{c.phone||'—'}</div><div className="text-xs text-slate-400">{c.email||''}</div></td><td className="p-3">{money(c.total)}</td><td className="p-3 text-amber-600">{money(c.pending)}</td><td className="p-3"><span className="rounded-full bg-[#172a57] px-3 py-1 text-xs text-white">{(c.status||'Active')==='Active'?t.active:t.inactive}</span></td><td className="relative p-3"><button onClick={e=>{e.stopPropagation();setMenu(menu===c.id?null:c.id)}} className="px-3 font-bold">•••</button>{menu===c.id&&<div className="absolute z-20 w-40 rounded-lg border border-slate-200 bg-white p-1 shadow-lg dark:border-[#24365f] dark:bg-[#111a2c]"><button onClick={e=>{e.stopPropagation();onOpenCustomer(c.id)}} className="flex w-full items-center gap-2 rounded p-2 hover:bg-slate-50 dark:hover:bg-white/5"><I name="◉"/>{t.profile}</button><button onClick={e=>{e.stopPropagation();openEdit(c)}} className="flex w-full items-center gap-2 rounded p-2 hover:bg-slate-50 dark:hover:bg-white/5"><I name="✎"/>{t.edit}</button><button onClick={e=>{e.stopPropagation();remove(c)}} className="flex w-full items-center gap-2 rounded p-2 text-red-500 hover:bg-red-50 dark:hover:bg-red-500/10"><I name="⌫"/>{t.del}</button></div>}</td></tr>)}</tbody></table></div>}</div>
  {modal&&createPortal(<div role="presentation" onMouseDown={e=>{if(e.target===e.currentTarget)setModal(false)}} className="modal-backdrop"><div role="dialog" aria-modal="true" className="modal-card w-full max-w-md p-5"><div className="mb-4 flex items-center justify-between"><h3 className="text-lg font-extrabold">{editing?t.modalEdit:t.modalAdd}</h3><button onClick={()=>setModal(false)}>×</button></div><label className="text-xs font-semibold">{t.name} *</label><input autoFocus className="form-control mt-1" value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder={t.namePh}/><div className="mt-3 grid grid-cols-1 gap-3 sm:grid-cols-2"><div><label className="text-xs font-semibold">{t.phone}</label><input className="form-control mt-1" value={form.phone||''} onChange={e=>setForm({...form,phone:e.target.value})} placeholder={t.phonePh}/></div><div><label className="text-xs font-semibold">{t.email}</label><input className="form-control mt-1" value={form.email||''} onChange={e=>setForm({...form,email:e.target.value})} placeholder={t.emailPh}/></div></div><label className="mt-3 block text-xs font-semibold">{t.address}</label><input className="form-control mt-1" value={form.address||''} onChange={e=>setForm({...form,address:e.target.value})} placeholder={t.addressPh}/><label className="mt-3 block text-xs font-semibold">{t.notes}</label><textarea className="form-control mt-1 min-h-[80px]" value={form.notes||''} onChange={e=>setForm({...form,notes:e.target.value})} placeholder={t.notesPh}/><label className="mt-3 flex items-center gap-2"><input type="checkbox" checked={!!form.vip} onChange={e=>setForm({...form,vip:e.target.checked})}/><span>☆</span>{t.vipCustomer}</label><div className="mt-5 grid grid-cols-[1fr_auto] gap-2"><button onClick={persist} className="h-10 rounded-lg bg-[#172a57] font-bold text-white">{t.save}</button><button onClick={()=>setModal(false)} className="h-10 rounded-lg border px-4">{t.cancel}</button></div></div></div>,document.body)}
 </div>
}
function Card({title,value,icon,accent}:{title:string;value:string;icon:string;accent:string}){return <div className="stat-card rounded-xl border border-slate-200 border-s-4 bg-white p-4 shadow-sm dark:border-[#24365f] dark:bg-[#111a2c]"><div className="flex items-center justify-between"><div><div className="text-sm text-slate-500">{title}</div><div className="mt-1 text-2xl font-extrabold">{value}</div></div><div className={`grid h-10 w-10 place-items-center rounded-xl ${accent}`}>{icon}</div></div></div>}
