import { useEffect, useMemo, useState } from 'react'
import { AlertTriangle, CalendarDays, CheckCircle2, Clock3, CreditCard, Printer, Search } from 'lucide-react'
import type { Language } from '../i18n'

const read = (key:string):any[] => { try { const v=JSON.parse(localStorage.getItem(key)||'[]'); return Array.isArray(v)?v:[] } catch { return [] } }
const n=(v:any)=>Number.parseFloat(String(v??0))||0
const money=(v:number,c='AFN')=>`${v.toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2})} ${c==='AFN'?'؋':c}`
const dateOf=(x:any)=>String(x.date||x.createdAt||x.invoiceDate||'').slice(0,10)
const inRange=(d:string,f:string)=>{if(!d||f==='all')return true;const x=new Date(d),now=new Date();if(Number.isNaN(x.getTime()))return true; if(f==='today')return x.toDateString()===now.toDateString(); if(f==='week')return now.getTime()-x.getTime()<=7*864e5; if(f==='month')return x.getMonth()===now.getMonth()&&x.getFullYear()===now.getFullYear(); if(f==='year')return x.getFullYear()===now.getFullYear(); return true}

const txt={
 English:{title:'Loan Management',sub:'Track and manage customer credit balances',print:'Print Report',active:'Active Loans',paid:'Paid Loans',pending:'Pending Loans',overdue:'Overdue Loans',search:'Search by invoice or customer...',all:'All',pendingS:'Pending',paidS:'Paid',overdueS:'Overdue',allTime:'All time',today:'Today',week:'Weekly',month:'Monthly',year:'Yearly',invoice:'Invoice',customer:'Customer',total:'Total',paidCol:'Paid',balance:'Balance',status:'Status',date:'Date',empty:'No loan found',hint:'Credit balances created from billing appear here automatically.'},
 دری:{title:'مدیریت قرض‌ها',sub:'پیگیری و مدیریت قرض‌های مشتریان',print:'چاپ گزارش',active:'قرض‌های فعال',paid:'قرض‌های پرداخت شده',pending:'قرض‌های معلق',overdue:'قرض‌های معوق',search:'جستجو با فاکتور یا مشتری...',all:'همه',pendingS:'معلق',paidS:'پرداخت شده',overdueS:'معوق',allTime:'همه وقت',today:'امروز',week:'هفتگی',month:'ماهانه',year:'سالانه',invoice:'فاکتور',customer:'مشتری',total:'مجموع',paidCol:'پرداخت شده',balance:'باقیمانده',status:'وضعیت',date:'تاریخ',empty:'قرضی یافت نشد',hint:'قرض‌ها هنگام ایجاد فروش نسیه از صورت‌حساب به صورت خودکار اینجا نمایش داده می‌شوند.'},
 پښتو:{title:'د قرضونو مدیریت',sub:'د پیرودونکو قرضونه تعقیب او مدیریت کړئ',print:'راپور چاپ',active:'فعال قرضونه',paid:'ورکړل شوي قرضونه',pending:'پاتې قرضونه',overdue:'ځنډېدلي قرضونه',search:'د فاکتور یا پیرودونکي له مخې لټون...',all:'ټول',pendingS:'پاتې',paidS:'ورکړل شوی',overdueS:'ځنډېدلی',allTime:'ټول وخت',today:'نن',week:'اونیز',month:'میاشتنی',year:'کلنی',invoice:'فاکتور',customer:'پیرودونکی',total:'ټول',paidCol:'ورکړل شوی',balance:'پاتې',status:'حالت',date:'نېټه',empty:'قرض ونه موندل شو',hint:'د پور پر اساس خرڅلاو قرضونه په اتومات ډول دلته ښکاري.'}
} as const

export default function Loans({language}:{language:Language}){
 const t=txt[language], [,refresh]=useState(0),[q,setQ]=useState(''),[status,setStatus]=useState('all'),[period,setPeriod]=useState('all')
 useEffect(()=>{const f=()=>refresh(x=>x+1);addEventListener('pharma:data-changed',f);addEventListener('storage',f);return()=>{removeEventListener('pharma:data-changed',f);removeEventListener('storage',f)}},[])
 const rows=useMemo(()=>read('billingInvoices').map((x:any)=>{const total=n(x.total??x.grandTotal),paid=n(x.paidAmount??x.paid),balance=Math.max(0,n(x.balance??x.remaining??(total-paid)));const due=String(x.dueDate||'');const overdue=balance>0&&due&&new Date(due)<new Date();return {...x,total,paid,balance,_status:balance<=0?'paid':overdue?'overdue':'pending'}}),[q,status,period])
 const filtered=rows.filter((x:any)=>{const s=`${x.invoiceNumber||x.invoice||x.id||''} ${x.customerName||x.customer||''}`.toLowerCase();return (!q||s.includes(q.toLowerCase()))&&(status==='all'||x._status===status)&&inRange(dateOf(x),period)})
 const sum=(f:(x:any)=>boolean,key='balance')=>rows.filter(f).reduce((a:any,x:any)=>a+n(x[key]),0)
 return <div className="space-y-5">
  <div className="flex items-start justify-between gap-3"><div><h1 className="text-[24px] font-bold">{t.title}</h1><p className="text-sm text-slate-500 dark:text-slate-300">{t.sub}</p></div><button onClick={()=>window.print()} className="h-10 rounded-lg border border-slate-200 bg-white px-4 text-sm font-semibold dark:border-[#314260] dark:bg-[#111a2c]"><Printer size={16} className="inline me-2"/>{t.print}</button></div>
  <div className="grid gap-3 md:grid-cols-2 xl:grid-cols-4">{[[CreditCard,t.active,sum(x=>x.balance>0),'blue'],[CheckCircle2,t.paid,rows.filter(x=>x._status==='paid').length,'green'],[Clock3,t.pending,sum(x=>x._status==='pending'),'orange'],[AlertTriangle,t.overdue,sum(x=>x._status==='overdue'),'red']].map(([I,l,v,c]:any)=><div key={l} className={`rounded-xl border border-slate-200 bg-white p-5 shadow-sm dark:border-[#314260] dark:bg-[#111a2c] border-s-4 ${c==='blue'?'border-s-sky-500':c==='green'?'border-s-emerald-500':c==='orange'?'border-s-amber-500':'border-s-red-500'}`}><div className="flex items-center justify-between"><div><div className="text-sm text-slate-500 dark:text-slate-300">{l}</div><div className="mt-1 text-2xl font-bold">{typeof v==='number'&&l===t.paid?v:money(v)}</div></div><span className="grid h-10 w-10 place-items-center rounded-xl bg-slate-100 dark:bg-[#1c2942]"><I size={20}/></span></div></div>)}</div>
  <div className="rounded-xl border border-slate-200 bg-white p-4 shadow-sm dark:border-[#314260] dark:bg-[#111a2c]"><div className="flex flex-wrap gap-3"><div className="relative min-w-[260px] flex-1"><Search size={17} className="absolute start-3 top-2.5 text-slate-400"/><input value={q} onChange={e=>setQ(e.target.value)} placeholder={t.search} className="h-10 w-full rounded-lg border border-slate-200 bg-transparent ps-10 pe-3 text-sm dark:border-[#314260]"/></div><select value={status} onChange={e=>setStatus(e.target.value)} className="h-10 min-w-[150px] rounded-lg border border-slate-200 bg-white px-3 dark:border-[#314260] dark:bg-[#0d1728]"><option value="all">{t.all}</option><option value="pending">{t.pendingS}</option><option value="paid">{t.paidS}</option><option value="overdue">{t.overdueS}</option></select><select value={period} onChange={e=>setPeriod(e.target.value)} className="h-10 min-w-[145px] rounded-lg border border-slate-200 bg-white px-3 dark:border-[#314260] dark:bg-[#0d1728]"><option value="all">{t.allTime}</option><option value="today">{t.today}</option><option value="week">{t.week}</option><option value="month">{t.month}</option><option value="year">{t.year}</option></select></div></div>
  <div className="overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm dark:border-[#314260] dark:bg-[#111a2c]"><div className="border-b border-slate-200 p-4 font-bold dark:border-[#314260]">{t.title} ({filtered.length})</div>{filtered.length?<div className="overflow-x-auto"><table className="w-full text-sm"><thead className="bg-slate-50 text-slate-500 dark:bg-[#0d1728] dark:text-slate-300"><tr>{[t.invoice,t.customer,t.total,t.paidCol,t.balance,t.status,t.date].map(h=><th key={h} className="px-4 py-3 text-start">{h}</th>)}</tr></thead><tbody>{filtered.map((x:any)=><tr key={x.id||x.invoiceNumber} className="border-t border-slate-100 dark:border-[#273653]"><td className="px-4 py-4 font-mono">{x.invoiceNumber||x.invoice||x.id}</td><td className="px-4 py-4">{x.customerName||x.customer||'—'}</td><td className="px-4 py-4">{money(x.total,x.currency)}</td><td className="px-4 py-4 text-emerald-600">{money(x.paid,x.currency)}</td><td className="px-4 py-4 text-amber-600">{money(x.balance,x.currency)}</td><td className="px-4 py-4"><span className={`rounded-full px-2 py-1 text-xs ${x._status==='paid'?'bg-emerald-100 text-emerald-700':x._status==='overdue'?'bg-red-100 text-red-700':'bg-amber-100 text-amber-700'}`}>{x._status==='paid'?t.paidS:x._status==='overdue'?t.overdueS:t.pendingS}</span></td><td className="px-4 py-4">{dateOf(x)||'—'}</td></tr>)}</tbody></table></div>:<div className="grid min-h-[250px] place-items-center text-center"><div><CalendarDays className="mx-auto text-slate-300" size={42}/><div className="mt-3 font-bold">{t.empty}</div><div className="mt-1 text-sm text-slate-500">{t.hint}</div></div></div>}</div>
 </div>
}
