import { useMemo, useState } from 'react'
import { Activity, ArrowLeft, Box, Download, FileText, MoreHorizontal, Plus, Printer, RefreshCcw, TrendingUp, X } from 'lucide-react'
import type { Language } from '../i18n'

type Supplier={id:string;name?:string;supplierName?:string;currency?:string;balance?:number;openingBalance?:number;createdAt?:string;phone?:string;address?:string}
type Purchase={id:string;supplierId?:string;supplierName?:string;productId?:string;deviceName?:string;name?:string;category?:string;quantity?:number;unit?:string;unitPrice?:number;currency?:string;totalPurchaseValue?:number;paidAmount?:number;remainAmount?:number;purchaseDate?:string;date?:string;createdAt?:string;source?:string}
type Payment={id:string;supplierId?:string;supplierName?:string;amount:number;currency:string;direction?:string;type?:string;recordType?:string;date?:string;createdAt?:string;description?:string}
type Product={id:string;name:string;code?:string;quantity:number;unit:string;purchase:number;selling:number;supplierId?:string}

function load<T>(key:string,fallback:T):T{try{const r=localStorage.getItem(key);return r?JSON.parse(r):fallback}catch{return fallback}}
function save(key:string,v:unknown){localStorage.setItem(key,JSON.stringify(v));window.dispatchEvent(new CustomEvent('pharma:data-changed'))}
const n=(v:unknown)=>Number.parseFloat(String(v??0))||0
const round=(v:number)=>Math.round((v+Number.EPSILON)*100)/100
const sym=(c='AFN')=>({AFN:'؋',USD:'$',EUR:'€',GBP:'£',SAR:'ریال',PKR:'Rs'} as Record<string,string>)[c]||c
const money=(v:number,c='AFN')=>`${v.toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2})} ${sym(c)}`

const text={
English:{portal:'Supplier Portal',account:'Account',printStatement:'Print Statement',current:'Current Balance',previous:'Previous Balance',settled:'Settled',addAdjustment:'Add Adjustment',all:'All',ledger:'Supplier Ledger',goods:'Goods',profit:'Profit',activity:'Activity Log',date:'Date',description:'Description',debit:'Debit',credit:'Credit',balance:'Balance',currency:'Currency',total:'Total',goodsTitle:'Goods from this supplier',printGoods:'Print Goods',downloadGoods:'Download Goods',name:'Name',code:'Code',imported:'Total Imported',sold:'Total Sold',remaining:'Remaining',purchase:'Purchase Price',selling:'Selling Price',profitUnit:'Profit / Unit',grossProfit:'Gross Profit',totalSales:'Total Sales Value',totalPurchase:'Total Purchase Value',noSales:'No sales recorded for this supplier goods yet',activityTitle:'Activity Log',printActivity:'Print Activity',downloadActivity:'Download Activity',adjustment:'Adjustment',type:'Type',amount:'Amount',note:'Note',cancel:'Cancel',save:'Save Adjustment',wePay:'Debit (increase supplier balance)',supplierPays:'Credit (payment / reduce balance)',noData:'No records found'},
دری:{portal:'پورتال تأمین‌کننده',account:'حساب',printStatement:'چاپ صورت‌حساب',current:'مانده فعلی',previous:'مانده قبلی',settled:'تسویه شده',addAdjustment:'افزودن تعدیل',all:'همه',ledger:'دفتر تأمین‌کننده',goods:'کالاها',profit:'سود',activity:'سابقه فعالیت',date:'تاریخ',description:'توضیحات',debit:'برداشت',credit:'واریز',balance:'مانده',currency:'واحد پول',total:'مجموع',goodsTitle:'کالاهای این تأمین‌کننده',printGoods:'چاپ کالاها',downloadGoods:'دانلود کالاها',name:'نام',code:'کد',imported:'مجموع وارد شده',sold:'مجموع فروخته شده',remaining:'باقیمانده',purchase:'قیمت خرید',selling:'قیمت فروش',profitUnit:'سود/واحد',grossProfit:'سود ناخالص',totalSales:'ارزش کل فروش',totalPurchase:'ارزش کل خرید',noSales:'هنوز فروشی برای کالاهای این تأمین‌کننده ثبت نشده',activityTitle:'سابقه فعالیت',printActivity:'چاپ فعالیت',downloadActivity:'دانلود فعالیت',adjustment:'تعدیل',type:'نوع',amount:'مبلغ',note:'یادداشت',cancel:'لغو',save:'ذخیره تعدیل',wePay:'بدهکار — افزایش مانده تأمین‌کننده',supplierPays:'بستانکار — پرداخت / کاهش مانده',noData:'ریکاردی یافت نشد'},
پښتو:{portal:'د عرضه کوونکي پورټل',account:'حساب',printStatement:'حساب چاپ',current:'اوسنی بیلانس',previous:'مخکینی بیلانس',settled:'تسویه شوی',addAdjustment:'تعدیل اضافه کړئ',all:'ټول',ledger:'د عرضه کوونکي دفتر',goods:'توکي',profit:'ګټه',activity:'فعالیتونه',date:'نېټه',description:'تشریح',debit:'پور',credit:'کریډیټ',balance:'بیلانس',currency:'اسعار',total:'ټول',goodsTitle:'د دې عرضه کوونکي توکي',printGoods:'توکي چاپ',downloadGoods:'توکي ډاونلوډ',name:'نوم',code:'کوډ',imported:'ټول داخل شوي',sold:'ټول پلورل شوي',remaining:'پاتې',purchase:'د پېرود بیه',selling:'د پلور بیه',profitUnit:'ګټه/واحد',grossProfit:'ناخالصه ګټه',totalSales:'د پلور ټول ارزښت',totalPurchase:'د پېرود ټول ارزښت',noSales:'تر اوسه د دې عرضه کوونکي د توکو پلور نشته',activityTitle:'فعالیتونه',printActivity:'فعالیت چاپ',downloadActivity:'فعالیت ډاونلوډ',adjustment:'تعدیل',type:'ډول',amount:'مبلغ',note:'یادښت',cancel:'لغوه',save:'تعدیل خوندي کړئ',wePay:'ډیبیټ — د عرضه کوونکي بیلانس زیاتوي',supplierPays:'کریډیټ — تادیه / بیلانس کموي',noData:'ریکارډ نشته'}
} as const

export default function SupplierDetails({supplierId,language,onBack}:{supplierId:string;language:Language;onBack:()=>void}){
 const t=text[language]; const suppliers=load<Supplier[]>('suppliers',[]); const supplier=suppliers.find(s=>String(s.id)===String(supplierId)); const currency=supplier?.currency||'AFN';
 const [godownEntries,setGodownEntries]=useState<any[]>(()=>load('godownEntries',[])); const purchases=load<Purchase[]>('supplierPurchases',[]); const products=load<Product[]>('products',[]); const invoices=load<any[]>('billingInvoices',[])
 const [tab,setTab]=useState<'ledger'|'goods'|'profit'|'activity'>('ledger'); const [adjustOpen,setAdjustOpen]=useState(false); const [adjust,setAdjust]=useState({type:'debit',amount:0,note:''})
 const name=supplier?.supplierName||supplier?.name||'Supplier'; const mine=purchases.filter(p=>String(p.supplierId||'')===String(supplierId)||p.supplierName===name)
 const adjustments=godownEntries.flatMap((entry:any)=>(entry.adjustments||[]).filter((a:any)=>String(a.supplierId||entry.supplierId||'')===String(supplierId)).map((a:any)=>({...a,supplierId:a.supplierId||entry.supplierId})))
 const purchaseTotal=round(mine.reduce((s,p)=>s+n(p.totalPurchaseValue),0)); const purchasePaid=round(mine.reduce((s,p)=>s+n(p.paidAmount),0));
 const debitAdj=round(adjustments.filter((p:any)=>String(p.type).toLowerCase()==='debit').reduce((s:number,p:any)=>s+n(p.amount),0)); const creditAdj=round(adjustments.filter((p:any)=>String(p.type).toLowerCase()==='credit').reduce((s:number,p:any)=>s+n(p.amount),0));
 const opening=n(supplier?.openingBalance??supplier?.balance); const current=round(opening+purchaseTotal-purchasePaid+debitAdj-creditAdj)
 const goods=useMemo(()=>products.filter(p=>String(p.supplierId||'')===String(supplierId)).map(p=>{const sold=invoices.reduce((s,inv)=>s+(inv.items||[]).filter((i:any)=>String(i.productId)===String(p.id)).reduce((x:number,i:any)=>x+n(i.qty),0),0); const imported=mine.filter(x=>String(x.productId||'')===String(p.id)).reduce((s,x)=>s+n(x.quantity),0)||n(p.quantity)+sold; return {...p,sold,imported,remaining:Math.max(0,imported-sold),gross:round(sold*(n(p.selling)-n(p.purchase)))} }),[products,invoices,mine,supplierId])
 const gross=round(goods.reduce((s,g)=>s+g.gross,0)); const salesValue=round(goods.reduce((s,g)=>s+g.sold*n(g.selling),0)); const purchaseValue=round(goods.reduce((s,g)=>s+g.imported*n(g.purchase),0))
 const ledger=[...mine.map(p=>({id:p.id,date:p.purchaseDate||p.date||p.createdAt||'',description:`Product Restock: ${n(p.quantity)} × ${p.deviceName||p.name||'Product'} ${p.unit||''}`,debit:n(p.totalPurchaseValue),credit:n(p.paidAmount),currency:p.currency||currency})),...adjustments.map((p:any)=>({id:p.id,date:p.date||p.createdAt||'',description:p.reason||p.description||t.adjustment,debit:String(p.type).toLowerCase()==='debit'?n(p.amount):0,credit:String(p.type).toLowerCase()==='credit'?n(p.amount):0,currency:p.currency||currency}))].sort((a,b)=>String(a.date).localeCompare(String(b.date)))
 let run=opening; const ledgerRows=ledger.map(r=>{run=round(run+r.debit-r.credit);return{...r,balance:run}})
 const addAdjustment=(e:React.FormEvent)=>{e.preventDefault();if(adjust.amount<=0)return;const now=new Date().toISOString();const row={id:`adjustment-${Date.now()}`,supplierId,amount:n(adjust.amount),currency,type:adjust.type,balanceDelta:adjust.type==='credit'?-n(adjust.amount):n(adjust.amount),date:now.slice(0,10),createdAt:now,reason:adjust.note||t.adjustment};const entry={id:`supplier-adjustment-${row.id}`,supplierId,currency,date:row.date,createdAt:now,type:'supplier-adjustment',total:0,paid:0,remaining:0,rows:[],adjustments:[row]};const next=[entry,...godownEntries];setGodownEntries(next);save('godownEntries',next);const tx=load<any[]>('transactions',[]);save('transactions',[{id:`supplier-${row.id}`,type:row.type==='credit'?'expense':'income',transactionType:row.type==='credit'?'withdraw':'deposit',title:`${row.type==='debit'?'Supplier debit':'Supplier credit'} - ${name}`,amount:row.amount,date:row.date,description:row.reason,source:'cash-wallet',referenceSource:'supplier-adjustment',category:'Cash Wallet',referenceId:supplierId,currency},...tx]);setAdjustOpen(false);setAdjust({type:'debit',amount:0,note:''})}
 const print=()=>window.print(); const download=(kind:string)=>{const rows=kind==='goods'?goods.map(g=>[g.name,g.code||'',g.imported,g.sold,g.remaining,g.purchase,g.selling,g.gross]):ledgerRows.map(r=>[r.date,r.description,r.debit,r.credit,r.balance,r.currency]); const csv=rows.map(r=>r.map(v=>`"${String(v).replace(/"/g,'""')}"`).join(',')).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download=`supplier-${kind}.csv`;a.click();URL.revokeObjectURL(a.href)}
 return <div className="w-full pb-8"><div className="flex flex-col gap-3 lg:flex-row lg:items-start lg:justify-between"><div className="flex items-start gap-3"><button onClick={onBack} className="grid h-10 w-10 place-items-center rounded-lg border border-slate-200 dark:border-[#24365f]"><ArrowLeft size={18}/></button><div><h1 className="text-2xl font-extrabold">{t.portal}: {name}</h1><p className="text-sm text-slate-500">{currency} • {new Date(supplier?.createdAt||Date.now()).toLocaleDateString()}</p></div></div><button onClick={print} className="inline-flex h-10 items-center gap-2 self-start rounded-lg border border-slate-200 px-4 text-sm font-semibold dark:border-[#24365f]"><Printer size={16}/>{t.printStatement}</button></div>
 <div className="app-panel mt-5 rounded-xl border border-slate-300 bg-white p-5 dark:border-[#33456d] dark:bg-[#111a2c]"><div className="flex flex-col gap-5 md:flex-row md:items-center md:justify-between"><div><div className="text-sm font-bold">{t.account}: {name} — {currency}</div><div className="mt-1 text-xs text-slate-400">{new Date().toLocaleDateString()}</div></div><div className="flex gap-8"><div><div className="text-xs text-slate-400">{t.current}</div><div className="text-2xl font-extrabold">{money(Math.abs(current),currency)}</div><div className="text-xs text-slate-400">{current===0?t.settled:current>0?'Payable':'Receivable'}</div></div><div><div className="text-xs text-slate-400">{t.previous}</div><div className="text-xl font-bold">{money(Math.abs(opening),currency)}</div></div></div></div></div>
 <div className="mt-5 flex flex-wrap justify-end gap-3"><button onClick={()=>setAdjustOpen(true)} className="inline-flex h-10 items-center gap-2 rounded-lg border border-slate-200 px-4 text-sm font-semibold dark:border-[#24365f]"><RefreshCcw size={15}/>{t.addAdjustment}</button></div>
 <div className="mt-5 flex flex-wrap gap-2">{([['ledger',FileText,t.ledger],['goods',Box,t.goods],['profit',TrendingUp,t.profit],['activity',Activity,t.activity]] as const).map(([k,I,l])=><button key={k} onClick={()=>setTab(k)} className={`inline-flex h-9 items-center gap-2 rounded-lg px-3 text-sm font-semibold ${tab===k?'bg-white shadow-sm dark:bg-white/10':'text-slate-500'}`}><I size={15}/>{l}</button>)}</div>
 {tab==='ledger'&&<div className="mt-4 overflow-x-auto"><table className="w-full min-w-[850px] text-sm"><thead className="bg-[#172a57] text-white"><tr><Th>{t.date}</Th><Th>{t.description}</Th><Th>{t.debit}</Th><Th>{t.credit}</Th><Th>{t.balance}</Th><Th>{t.currency}</Th><Th></Th></tr></thead><tbody>{ledgerRows.map(r=><tr key={r.id} className="border-b border-slate-200 dark:border-[#24365f]"><Td>{String(r.date).slice(0,10)}</Td><Td>{r.description}</Td><Td>{r.debit?money(r.debit,r.currency):'-'}</Td><Td>{r.credit?money(r.credit,r.currency):'-'}</Td><Td>{money(r.balance,r.currency)}</Td><Td>{r.currency}</Td><Td><MoreHorizontal size={16}/></Td></tr>)}{!ledgerRows.length&&<tr><td colSpan={7} className="p-10 text-center text-slate-400">{t.noData}</td></tr>}</tbody><tfoot className="bg-[#172a57] font-bold text-white"><tr><Td>{t.total}</Td><Td></Td><Td>{money(ledgerRows.reduce((s,r)=>s+r.debit,0),currency)}</Td><Td>{money(ledgerRows.reduce((s,r)=>s+r.credit,0),currency)}</Td><Td>{money(current,currency)}</Td><Td>{currency}</Td><Td></Td></tr></tfoot></table></div>}
 {tab==='goods'&&<div className="app-panel mt-4 overflow-hidden rounded-xl border border-slate-200 bg-white dark:border-[#24365f] dark:bg-[#111a2c]"><div className="flex flex-wrap items-center justify-between gap-3 p-5"><h3 className="font-bold">{t.goodsTitle} ({goods.length})</h3><div className="flex gap-2"><button onClick={print} className="inline-flex h-9 items-center gap-2 rounded-lg border px-3 text-sm"><Printer size={15}/>{t.printGoods}</button><button onClick={()=>download('goods')} className="inline-flex h-9 items-center gap-2 rounded-lg border px-3 text-sm"><Download size={15}/>{t.downloadGoods}</button></div></div><div className="overflow-x-auto"><table className="w-full min-w-[950px] text-sm"><thead className="bg-slate-50 dark:bg-white/5"><tr><Th>{t.name}</Th><Th>{t.code}</Th><Th>{t.imported}</Th><Th>{t.sold}</Th><Th>{t.remaining}</Th><Th>{t.purchase}</Th><Th>{t.selling}</Th><Th>{t.profitUnit}</Th></tr></thead><tbody>{goods.map(g=><tr key={g.id} className="border-t border-slate-100 dark:border-[#24365f]"><Td>{g.name}</Td><Td>{g.code||'-'}</Td><Td>{g.imported} {g.unit}</Td><Td>{g.sold} {g.unit}</Td><Td><b>{g.remaining} {g.unit}</b></Td><Td>{money(n(g.purchase),currency)}</Td><Td>{money(n(g.selling),currency)}</Td><Td className="text-emerald-500">{money(n(g.selling)-n(g.purchase),currency)}</Td></tr>)}</tbody></table></div></div>}
 {tab==='profit'&&<div className="mt-4"><div className="supplier-metrics grid gap-3"><Metric label={t.grossProfit} value={money(gross,currency)} tone="green"/><Metric label={t.totalSales} value={money(salesValue,currency)}/><Metric label={t.totalPurchase} value={money(purchaseValue,currency)} tone="red"/></div><div className="app-panel mt-4 rounded-xl border border-slate-200 bg-white p-5 dark:border-[#24365f] dark:bg-[#111a2c]"><h3 className="font-bold">{t.profit}</h3>{gross===0?<div className="p-10 text-center text-sm text-slate-400">{t.noSales}</div>:goods.filter(g=>g.sold>0).map(g=><div key={g.id} className="mt-3 flex justify-between border-t pt-3"><span>{g.name}</span><b className="text-emerald-500">{money(g.gross,currency)}</b></div>)}</div></div>}
 {tab==='activity'&&<div className="app-panel mt-4 rounded-xl border border-slate-200 bg-white p-5 dark:border-[#24365f] dark:bg-[#111a2c]"><div className="flex flex-wrap justify-between gap-3"><h3 className="font-bold">{t.activityTitle}</h3><div className="flex gap-2"><button onClick={print} className="inline-flex h-9 items-center gap-2 rounded-lg border px-3 text-sm"><Printer size={15}/>{t.printActivity}</button><button onClick={()=>download('activity')} className="inline-flex h-9 items-center gap-2 rounded-lg border px-3 text-sm"><Download size={15}/>{t.downloadActivity}</button></div></div><div className="mt-5 space-y-4">{ledgerRows.slice().reverse().map(r=><div key={r.id} className="relative pl-5 rtl:pl-0 rtl:pr-5"><span className="absolute left-0 top-2 h-2 w-2 rounded-full bg-red-500 rtl:left-auto rtl:right-0"/><div className="font-semibold">{r.description}</div><div className="text-xs text-slate-400">{new Date(r.date||Date.now()).toLocaleString()} • {money(r.balance,r.currency)}</div></div>)}</div></div>}
 {adjustOpen&&<div className="fixed inset-0 z-[80] grid place-items-center bg-black/70 p-4"><form onSubmit={addAdjustment} className="w-full max-w-md rounded-xl bg-white p-5 text-slate-900 shadow-2xl dark:bg-[#101827] dark:text-white"><div className="flex justify-between"><h2 className="text-lg font-bold">{t.addAdjustment}</h2><button type="button" onClick={()=>setAdjustOpen(false)}><X size={18}/></button></div><label className="mt-5 block text-sm font-semibold">{t.type}</label><select value={adjust.type} onChange={e=>setAdjust({...adjust,type:e.target.value})} className="form-control mt-1"><option value="debit">{t.wePay}</option><option value="credit">{t.supplierPays}</option></select><label className="mt-4 block text-sm font-semibold">{t.amount}</label><input type="number" min="0" step="0.01" value={adjust.amount} onChange={e=>setAdjust({...adjust,amount:n(e.target.value)})} className="form-control mt-1"/><label className="mt-4 block text-sm font-semibold">{t.note}</label><textarea value={adjust.note} onChange={e=>setAdjust({...adjust,note:e.target.value})} className="form-control mt-1 min-h-20 py-2"/><div className="mt-5 flex justify-end gap-2"><button type="button" onClick={()=>setAdjustOpen(false)} className="h-10 rounded-lg border px-4">{t.cancel}</button><button className="h-10 rounded-lg bg-[#172a57] px-4 font-bold text-white dark:bg-amber-500 dark:text-slate-950">{t.save}</button></div></form></div>}
 </div>
}
function Th({children}:{children?:React.ReactNode}){return <th className="px-4 py-3 text-start text-xs font-bold">{children}</th>};function Td({children,className=''}:{children?:React.ReactNode;className?:string}){return <td className={`px-4 py-3 ${className}`}>{children}</td>};function Metric({label,value,tone}:{label:string;value:string;tone?:'green'|'red'}){return <div className="app-panel rounded-xl border border-slate-200 bg-white p-5 dark:border-[#24365f] dark:bg-[#111a2c]"><div className="text-sm text-slate-500">{label}</div><div className={`mt-2 text-2xl font-extrabold ${tone==='green'?'text-emerald-500':tone==='red'?'text-red-500':''}`}>{value}</div></div>}
